language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

before_script:
   - rustup component add clippy || cargo install --git https://github.com/rust-lang/rust-clippy/ --force clippy

script:
  - cargo clippy --verbose --all-targets --all-features -- -D warnings
  - cargo test --verbose --all --release
  - cargo build --verbose --all --release
