language: rust

cache: cargo

rust:
  - stable
  - beta
  - nightly

script:
  - cargo clippy --verbose --all-targets --all-features -- -D warnings
  - cargo test --verbose --all --release
  - cargo build --verbose --all --release
