[package]
name = "cargo-x"
version = "0.3.6"
authors = ["Liu Chong <mail@liuchong.io>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/liuchong/cargo-x"
homepage = "https://github.com/liuchong/cargo-x"
description = """
A very simple third-party cargo subcommand to execute a custom command.
"""
keywords = ["x", "exec", "execute", "cmd", "command"]
edition = "2021"

[package.metadata.x]
lint = "cargo clippy --verbose --workspace --all-targets --all-features --release -- -D warnings"
test = "cargo test --verbose --workspace --all-targets --all-features --release"
build = "cargo build --verbose --workspace --all-targets --all-features --release"

[lib]
name = "cargo_x"
path = "src/lib.rs"

[profile.release]
panic = 'abort'

[dependencies]
anyhow = "1.0"
dirs = "6.0"
serde = { version = "1.0", features = ["derive"] }
toml = "1.0"
